name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Add deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$DEPLOY_KEY" > "$HOME/deploy_key"
          chmod 600 "$HOME/deploy_key"
      - name: rsync files
        run: |
          rsync -avhz -e "ssh -o StrictHostKeyChecking=no -i $HOME/deploy_key"  --delete . tom@93.90.202.66:/var/www/html/wordpress
